# Generated by Django 5.0 on 2023-12-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_basket_options_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='basket',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='subcategory_id',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='subcategories',
            old_name='category_id',
            new_name='category',
        ),
    ]
